[package]
name = "guardian-indicator"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "guardian-indicator"
path = "src/main.rs"

[dependencies]
guardian-client = { path = "../guardian-client" }
ksni = { version = "0.3", default-features = false, features = ["async-io"] }
tokio = { version = "1", features = ["rt", "macros", "signal", "time"] }

[lints]
workspace = true
