[package]
name = "guardian-daemon"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
zbus.workspace = true

[dev-dependencies]
guardian-core = { path = "../guardian-core" }
guardian-testkit = { path = "../guardian-testkit" }
roxmltree.workspace = true

[lints]
workspace = true
