[package]
name = "guardian-daemon"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "guardian-daemon"
path = "src/bin/guardian-daemon.rs"

[dependencies]
guardian-core = { path = "../guardian-core" }
guardian-provider-api = { path = "../guardian-provider-api" }
zbus = { workspace = true, features = ["blocking-api"] }

[dev-dependencies]
guardian-testkit = { path = "../guardian-testkit" }
roxmltree.workspace = true

[lints]
workspace = true
